runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /(.*)\.json
  static_files: client/build/\1.json
  upload: client/build/(.*)\.json
- url: /static
  static_dir: client/build/static
- url: /(.*)\.js
  static_files: client/build/\1.js
  upload: client/build/(.*)\.js
- url: /form(.*)
  script: personal.app
- url: .*
  static_files: client/build/index.html
  upload: client/build/index.html

#  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: latest
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?node_modules/
- ^(.*/)?src/
