runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: build/js

- url: /css
  static_dir: build/css

- url: /(.*\.(gif|jpg|png|js|css|pdf))
  static_files: \1
  upload: (.*\.(gif|jpg|png|js|css|pdf))

- url: /.*
  script: personal.app
#  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/
- src/  
- animsition/
- bootstrap/